[package]
name = "advent-of-code"
version = "0.1.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]

[dependencies]
failure = "0.1"
structopt = "0.1"
structopt-derive = "0.1"
clap = "*"
bit-vec = "*"
cgmath = "0.15"
sha2 = "*"
